# host.ui.yml
# ---
# playbook that runs our UI host task for any hosts in the `ui` group, providing AWS credentials in the environment

- hosts: ui
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
    AWS_REGION: "{{ aws_region }}"
  tasks:
      - include_tasks: tasks/ui/host.ui.task.yml