- hosts: ui
  gather_facts: true
  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
    AWS_REGION: "{{ aws_region }}"

  tasks:
    - include_tasks: tasks/ui/remove.ui.task.yml