# host_vars/vpc.ansibled.yml

vpc_cidr_block: 10.0.0.0/16

vpc_subnets:
  public-a:
    cidr: 10.0.1.0/24
    az: "{{ aws_region }}a"
  public-b:
    cidr: 10.0.2.0/24
    az: "{{ aws_region }}b"
  private-a:
    cidr: 10.0.3.0/24
    az: "{{ aws_region }}a"
  private-b:
    cidr: 10.0.4.0/24
    az: "{{ aws_region }}b"

vpc_security_groups:
  - name: vpc-iac-sg-allow-public-ssh
    description: "Allow public SSH"
    rules:
      - proto: tcp
        cidr_ip: 0.0.0.0/0
        ports:
          - 22
  - name: vpc-iac-sg-allow-public-http
    description: "Allow public web traffic"
    rules:
      - proto: tcp
        cidr_ip: 0.0.0.0/0
        ports:
          - 80
          - 8080
          - 443